backend:
  name: github
  repo: svkorovin-jpg/eala.energy-site
  branch: main
  client_id: Ov23liANKMS51YquK0hE

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "site"
    label: "Site content"
    files:
      - label: "Homepage"
        name: "home"
        file: "content/home.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Text", name: "body", widget: "markdown" }